name: SonarQube Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with NPM
      run: npm login --registry=https://registry.npmjs.org/ --always-auth --auth-only
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Build application
      run: npm install && npm run build

    - name: Start SonarQube
      run: docker run -d --name sonarqube -p 9000:9000 sonarqube:latest

    - name: Wait for SonarQube to start
      run: |
        while ! nc -z localhost 9000; do
          sleep 1
        done

    - name: Generate project token
      run: |
        TOKEN=$(curl -X POST \
               -u admin:admin \
               -H 'Content-Type: application/x-www-form-urlencoded' \
               -d 'name=my_project_token' \
               'http://localhost:9000/api/user_tokens/generate' | \
               jq -r '.token')

        echo "SONAR_TOKEN=$TOKEN" >> $GITHUB_ENV

    - name: Run SonarQube analysis
      run: docker run --network="host" -e SONAR_HOST_URL="http://localhost:9000" -e SONAR_TOKEN=$SONAR_TOKEN sonarsource/sonar-scanner-cli:4.6

    - name: Stop SonarQube
      run: docker stop sonarqube

    - name: Check SonarQube status
      run: curl -s -u admin:admin http://localhost:9000/api/system/status | jq .
