name: SonarQube Analysis
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  sonarqube_analysis:
    runs-on: ubuntu-latest
    container:
      image: sonarqube:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: npm ci
      - name: Setup SonarQube
        run: |
          echo "sonar.host.url=http://localhost:9000" >> .env
          echo "sonar.login=sqp_441b1af0cbcdd1a08a75ff2b8265ae1483a51d96" >> .env
      - name: Run SonarQube Scanner
        run: |
          npm run build
          sonar-scanner
        env:
          SONAR_TOKEN: "sqp_441b1af0cbcdd1a08a75ff2b8265ae1483a51d96"
