name: SonarQube Analysis

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube:community
        env:
          SONARQUBE_JDBC_URL: jdbc:postgresql://db:5432/sonar
          SONAR_JDBC_USERNAME: sonar
          SONAR_JDBC_PASSWORD: sonar
        options: >-
          --name sonarqube
          --publish 9000:9000
          --publish 9092:9092
          --network sonarnet
          --health-cmd="curl -f http://localhost:9000/api/system/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 9000:9000
          - 9092:9092

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install --save

      - name: Analyze code with SonarQube
        run: sonar-scanner
        env:
          SONAR_HOST_URL: http://sonarqube:9000
          SONAR_LOGIN: "sqp_441b1af0cbcdd1a08a75ff2b8265ae1483a51d96"
